services:
  nginx:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
  caddy:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
  traefik:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
  haproxy:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
